### ISSUE TITLE
Loot Tables TODO list.

### ISSUE THREAD

**Issue by ghost** [devs-immortal/The-Aether#49]
# Loot Tables TODO:

- [x] aether_bush
- [x] aether_farmland
- [x] aether_fern
- [x] aether_tall_grass
- [x] blueberry_bush
- [x] crystal_fence_gate
- [x] crystal_fence
- [x] crystal_log
- [x] crystal_planks
- [x] crystal_sapling
- [x] crystal_slab
- [x] crystal_stairs
- [x] dense_aercloud
- [x] flutegrass
- [x] frost_wisteria_hanger
- [x] frost_wisteria_hanger_plant
- [x] frost_wisteria_leaf_pile
- [x] frost_wisteria_leaves
- [x] frost_wisteria_sapling
- [ ] golden_oak_fence_gate
- [ ] golden_oak_fence
- [ ] golden_oak_planks
- [ ] golden_oak_slab
- [ ] golden_oak_stairs
- [ ] holiday_leaves
- [ ] icestone_slab
- [ ] icestone_stairs
- [ ] icestone_wall
- [ ] lavender_wisteria_hanger
- [ ] lavender_wisteria_hanger_plant
- [ ] lavender_wisteria_leaf_pile
- [ ] lavender_wisteria_leaves
- [ ] lavender_wisteria_sapling
- [ ] leaf_pile
- [ ] light_angelic_slab
- [ ] light_angelic_stairs
- [ ] light_angelic_stone_trapped
- [ ] light_angelic_wall
- [ ] light_hellfire_slab
- [ ] light_hellfire_stairs
- [ ] light_hellfire_stone_trapped
- [ ] light_hellfire_wall
- [ ] light_sentry_slab
- [ ] light_sentry_stairs
- [ ] light_sentry_stone
- [ ] light_sentry_wall
- [ ] mossy_holystone_brick
- [ ] mossy_holystone_brick_slab
- [ ] mossy_holystone_brick_stairs
- [ ] mossy_holystone_brick_wall
- [ ] potted_purple_flower
- [ ] potted_white_flower
- [x] quicksoil_glass_pane
- [ ] rootcap
- [ ] rose_wisteria_hanger
- [ ] rose_wisteria_hanger_plant
- [ ] rose_wisteria_leaf_pile
- [ ] rose_wisteria_leaves
- [ ] rose_wisteria_sapling
- [ ] sentry_slab
- [ ] sentry_stairs
- [ ] sentry_stone_cracked
- [ ] sentry_stone_trapped
- [ ] sentry_wall
- [x] stripped_crystal_log
- [ ] stripped_golden_oak_log
- [ ] stripped_skyroot_log
- [ ] stripped_wisteria_log
- [ ] wisteria_fence_gate
- [ ] wisteria_fence
- [ ] wisteria_hanger
- [ ] wisteria_log
- [ ] wisteria_planks
- [ ] wisteria_slab
- [ ] wisteria_stairs

**Comment by diabolical17** [comment]
Updated, removed duplicates.

**Comment by MBatt1** [comment]
all current blocks have (verified to be) working loot tables
